# remap prefix from 'C-b' to 'C-a'
# unbind C-b
# set-option -g prefix C-a
# bind-key C-a send-prefix
set -g base-index 1

# Easy config reload
bind-key r source-file ~/.tmux.conf \; display-message "tmux.conf reloaded."

# vi is good
setw -g mode-keys vi

# mouse behavior
setw -g mouse on

# Set scoll back buffer size
set-option -g history-limit 10000

# Colour!
# set-option -g default-terminal screen-256color

# use vim-like keys for splits and windows
unbind '"'
unbind %
bind-key v split-window -h
bind-key s split-window -v

# switch panes using Alt-arrow without prefix
bind -n M-Left select-pane -L
bind -n M-Right select-pane -R
bind -n M-Up select-pane -U
bind -n M-Down select-pane -D
# switch panes using Alt-vi without prefix
bind-key -n M-h select-pane -L
bind-key -n M-j select-pane -D
bind-key -n M-k select-pane -U
bind-key -n M-l select-pane -R

# Move windows
# bind-key C-o rotate-window

# bind-key 'v' copy-mode
bind-key 'p' paste-buffer

# Setup 'v' to begin selection as in Vim
bind-key -T copy-mode-vi v send -X begin-selection
# bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# Update default binding of `Enter` to also use copy-pipe
# unbind -T copy-mode-vi Enter
# bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "reattach-to-user-namespace pbcopy"

# set -g @yank_selection 'clipboard' # or 'secondary' or 'primary'
# bind -T copy-mode C-c send -X copy-pipe-no-clear "xsel -i --clipboard"
# bind -T copy-mode-vi C-c send -X copy-pipe-no-clear "xsel -i --clipboard"
# set -g @yank_action 'copy-pipe-no-clear'

### List of plugins ###
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
# set -g @plugin 'christoomey/vim-tmux-navigator'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'dracula/tmux'
# set -g @plugin 'tmux-plugins/tmux-continuum'

# Dracula styling (full/minimal)
# set -g @dracula-plugins "network network-bandwidth network-ping cpu-usage gpu-usage ram-usage battery time"
set -g @dracula-plugins "cpu-usage ram-usage time battery"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run '~/.tmux/plugins/tpm/tpm'

