return {
  -- 	{
  -- 		"nvimtools/none-ls.nvim",
  -- 		dependencies = {
  -- 			"nvimtools/none-ls-extras.nvim",
  -- 			"gbprod/none-ls-shellcheck.nvim",
  -- 		},
  -- 		config = function()
  -- 			local null_ls = require("null-ls")
  -- 			null_ls.setup({
  -- 				sources = {
  -- 					-- https://github.com/nvimtools/none-ls.nvim/blob/main/doc/BUILTINS.md
  -- 					null_ls.builtins.formatting.stylua,
  -- 					-- null_ls.builtins.formatting.clang_format,
  -- 					null_ls.builtins.completion.spell,
  -- 					-- require("none-ls.diagnostics.cpplint"),
  -- 				},
  -- 			})
  -- 			null_ls.register(require("none-ls-shellcheck.diagnostics"))
  -- 			null_ls.register(require("none-ls-shellcheck.code_actions"))
  -- 		end,
  -- 	},
}
